export { default as Admin } from './Admin';
export { default as DashboardLayout } from './DashboardLayout';
export { default as Errors } from './Errors';
export { default as HomeLayout } from './HomeLayout';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as Register } from './Register';
export { default as Widgets } from './Widgets';